name: CI Spring Boot

on:
  push:
    branches:
      - main
      - developpement
  pull_request:
    branches:
      - main
      - developpement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # ou 'corretto'
          java-version: '23'

      - name: Cache du dépôt Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compilation et tests Maven
        run: mvn clean verify --batch-mode -e -X
