name: CI/CD Spring Boot to Docker Hub

on:
  push:
    branches:
      - main
      - developpement
  pull_request:
    branches:
      - main
      - developpement

jobs:
  build_and_test:
    name: Build and Test Application
    runs-on: ubuntu-latest
    # outputs: # Décommentez et utilisez si vous avez besoin de passer des infos spécifiques
    # image_tag: ${{ steps.image_metadata.outputs.version }}

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Compilation et tests Maven
        run: mvn clean verify --batch-mode -e

  build_and_push_docker_image_to_main: # Nom de job plus spécifique
    name: Build and Push Docker Image to Main
    runs-on: ubuntu-latest
    needs: build_and_test # Dépend du succès du job de test
    # Condition pour ne s'exécuter QUE sur un push vers la branche 'main'
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/club-plus-backend # Nom de l'image corrigé
          # Tags spécifiques pour la branche main
          tags: |
            type=sha # Tag avec le SHA du commit
            type=raw,value=latest # Tag 'latest' pour la branche main
            # Vous pourriez ajouter d'autres tags si besoin, ex: version sémantique si vous en utilisez

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true # Pousse l'image
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
